Repository OpenLake/Introduction_CPP, pull requests merged in 2020-10, with the labels that each got.

#15 Fixed a single character typo in ReadMe.md
  README.md
  Sorting/quick.cpp
  Sorting/sorting.hpp
Labels: type-1

#18 Typo fixes in README
  README.md
Labels: type-1

#20 Fixed single character typo in Sorting\bubble.cpp
  Sorting/bubble.cpp
Labels: type-1

#22 fixed grammatical error in read me
  README.md
Labels: type-1

#21 Improved documentation of Sorting\bucket.cpp and Sorting\heap.cpp
  Sorting/bucket.cpp
  Sorting/heap.cpp
Labels: type-2

#26 Changed documentation of getMax function in radix.cpp
  Sorting/radix.cpp
Labels: type-2

#27 changed documentation in radix.cpp
  Sorting/radix.cpp
Labels: awaiting changes, type-2

#33 Documentation of insertion sort
  Sorting/insertion.cpp
Labels: type-2

#28 Changed code in insertion.cpp
  Sorting/insertion.cpp
Labels: type-3

#29 optimised pow function in radix.cpp
  Sorting/radix.cpp
Labels: type-3
